name: GDrive ZIP to Artifact

on:
  workflow_dispatch: # Pozwala na ręczne uruchomienie z panelu GitHub Actions

jobs:
  transfer:
    runs-on: ubuntu-latest

    steps:
      - name: Download ZIP from Google Drive
        run: |
          mkdir -p output
          
          # 1. Pobieramy ciasteczko i generujemy kod potwierdzający pominięcie skanowania antywirusowego Google
          curl -sc /tmp/cookie.txt "https://docs.google.com/uc?export=download&id=1ugH_mcYrIwuPgUJh4qeeE4AucdzbgNHI" > /dev/null
          CODE=$(curl -sL -b /tmp/cookie.txt "https://docs.google.com/uc?export=download&id=1ugH_mcYrIwuPgUJh4qeeE4AucdzbgNHI" | grep -o 'confirm=[^&]*' | head -n 1)
          
          # 2. Właściwe pobieranie pliku z użyciem wyciągniętego kodu
          curl -Lb /tmp/cookie.txt "https://docs.google.com/uc?export=download&${CODE}&id=1ugH_mcYrIwuPgUJh4qeeE4AucdzbgNHI" \
            -o "output/AP_S901EXXSDGZB6_S901EXXSDGZB6_MQB106584562_REV00_user_low_ship_MULTI_CERT_meta_OS16.tar.md5.zip" --fail

      - name: Upload as GitHub Artifact
        uses: actions/upload-artifact@v4
        with:
          # Nazwa paczki, którą zobaczysz w GitHubie
          name: rom-samsung-s22
          # Ścieżka do pobranego pliku
          path: "output/AP_S901EXXSDGZB6_S901EXXSDGZB6_MQB106584562_REV00_user_low_ship_MULTI_CERT_meta_OS16.tar.md5.zip"
          # Plik zniknie po 1 dniu, żeby nie zapchać darmowego limitu 500 MB na Twoim koncie
          retention-days: 1
