name: Download OTA

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Download OTA from PixelDrain
        run: |
          mkdir -p ota

          curl -L \
            "https://pixeldrain.com/api/file/pWud9sse?download" \
            -o ota.zip

          ls -lh ota.zip

      - name: Upload OTA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ota
          path: ota.zip
          if-no-files-found: error
          retention-days: 7
